from typing import Dict, Any, List

class NarrativeGenerator:
    @staticmethod
    def generate(impact_data: Dict[str, Any], active_scenarios: List[str]) -> str:
        ranking = impact_data.get("impact_ranking", [])
        score = impact_data.get("improvement_score", 0)
        
        if not ranking:
            return "Your current lifestyle parameters are already near optimal. Continue maintaining your healthy habits."
            
        top_scenario = ranking[0]["scenario"].replace("_", " ").title()
        
        narrative = f"Among all tested interventions, {top_scenario} produced the largest estimated risk reduction across our models. "
        
        if len(active_scenarios) > 0:
            narrative += f"By applying your selected changes, you have activated an estimated {score:.0f}% of your total lifestyle improvement potential. "
            if score > 50:
                narrative += "This indicates that these specific metabolic and cardiovascular modifications strongly influence your risk assessment. "
                
        narrative += "\n\nSimulation results are educational estimates generated by machine learning models and should not be considered medical advice."
        return narrative
